version: "3.8"

services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    image: outfit/database:1.0.0
    container_name: outfit-database
    restart: unless-stopped
    ports:
      - "5000:5000"

  database:
    build:
      context: database/
      dockerfile: Dockerfile
    image: outfit/backend:1.0.0
    container_name: outfit-backend
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "closet"
      MYSQL_USER: "closet"
      MYSQL_PASSWORD: "closet"
    ports:
      - "3360:3306"
    volumes:
      - ./database/data:/var/lib/mysql
