version: "3.8"

services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    image: outfit/frontend:1.0.0
    container_name: outfit-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
      # volumes:
      # - ./frontend/app:/app
      # - ./frontend/app/dist:/usr/share/nginx/html
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    image: outfit/backend:1.0.0
    container_name: outfit-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  database:
    build:
      context: database/
      dockerfile: Dockerfile
    image: outfit/database:1.0.0
    container_name: outfit-database
    restart: unless-stopped
    ports:
      - "3360:3306"
    volumes:
      - ./database/data:/var/lib/mysql

  cache:
    build:
      context: cache/
      dockerfile: Dockerfile
    image: outfit/redis:1.0.0
    container_name: outfit-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ./cache/data:/data
