[tool.poetry]
name = "data-analysis"
version = "0.1.0"
description = ""
authors = ["a920604a <a920604a@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
